# Generated by Django 5.0.6 on 2024-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(max_length=200)),
                ('is_vegetarian', models.BooleanField()),
                ('is_vegan', models.BooleanField()),
            ],
        ),
    ]
