# Generated by Django 5.0.6 on 2024-07-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=500, null=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('pizzas', models.ManyToManyField(related_name='orders', to='pizzas.pizza')),
            ],
        ),
    ]
